services:
  postgres:
    image: postgres:16.3
    container_name: learngraphql-postgres
    environment:
      POSTGRES_DB: learngraphql
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: learngraphql-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Spring Boot automatically maps these environment variables
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/learngraphql
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: false
      SPRING_GRAPHQL_GRAPHIQL_ENABLED: true
    ports:
      - "8080:8080"

volumes:
  postgres_data:
